name = "test08"
main = "_workers.js"
compatibility_date = "2023-05-26"
# node_compat = true
us.kg = true

[vars]
PROXYIP = "103.249.134.55:443"
UUID = "eef51130-c3b0-4a03-93a3-8bfe6514c9ed"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
