name = "test03"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
us.kg = true

[vars]
PROXYIP = "146.103.49.150:2053"
UUID = "80337eae-aeaa-4f0a-957a-73d0998d297d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
