name = "test05"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
us.kg = true

[vars]
PROXYIP = "146.103.49.150:2053"
UUID = "c333650a-cb55-11ef-9cd2-0242ac120002"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
